In [1]:
import numpy as np

In [3]:
arr = np.arange(10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[5]

5

In [6]:
arr[5:8]

array([5, 6, 7])

In [7]:
arr[5:8] = 12

In [8]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [9]:
arr[:]

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [11]:
arr2d = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                [13,14,15,16]])

In [12]:
arr2d[2, :]

array([ 9, 10, 11, 12])

In [13]:
arr2d[1:3, ]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
arr2d[:,3]

array([ 4,  8, 12, 16])

In [15]:
arr2d[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [16]:
arr2d[:2, 1:3] = 0

In [17]:
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [22]:
names = np.array(["Charles","Kilho","Hayoung","Charles","Hayoung","Kilho","Kilho"])
data = np.random.randn(7,4)

In [23]:
names

array(['Charles', 'Kilho', 'Hayoung', 'Charles', 'Hayoung', 'Kilho',
       'Kilho'], dtype='<U7')

In [24]:
data

array([[ 0.17053133, -0.77796288,  0.315862  ,  2.28607762],
       [-0.3198273 ,  0.16089829, -0.77768823, -1.05167028],
       [ 0.46305118, -0.75310701, -0.90742382,  0.61474453],
       [ 2.1697109 ,  0.70864324,  0.44073562,  0.48966493],
       [-1.77238332,  0.6272571 ,  0.47058162, -1.04944685],
       [-1.63379904, -0.75766892, -0.59356889,  0.45998309],
       [ 0.09248822, -1.7690092 ,  0.41896328, -0.2265991 ]])

In [25]:
names == "Charles"

array([ True, False, False,  True, False, False, False])

In [26]:
data[names == "Charles", :]

array([[ 0.17053133, -0.77796288,  0.315862  ,  2.28607762],
       [ 2.1697109 ,  0.70864324,  0.44073562,  0.48966493]])

In [27]:
data[names == "Kilho", :]

array([[-0.3198273 ,  0.16089829, -0.77768823, -1.05167028],
       [-1.63379904, -0.75766892, -0.59356889,  0.45998309],
       [ 0.09248822, -1.7690092 ,  0.41896328, -0.2265991 ]])

In [29]:
data[(names == "Charles")| (names == "Kilho"), :]

array([[ 0.17053133, -0.77796288,  0.315862  ,  2.28607762],
       [-0.3198273 ,  0.16089829, -0.77768823, -1.05167028],
       [ 2.1697109 ,  0.70864324,  0.44073562,  0.48966493],
       [-1.63379904, -0.75766892, -0.59356889,  0.45998309],
       [ 0.09248822, -1.7690092 ,  0.41896328, -0.2265991 ]])

In [30]:
data[:,3]

array([ 2.28607762, -1.05167028,  0.61474453,  0.48966493, -1.04944685,
        0.45998309, -0.2265991 ])

In [31]:
data[:,3] < 0

array([False,  True, False, False,  True, False,  True])

In [32]:
data[data[:,3]<0,:] = 0

In [33]:
data

array([[ 0.17053133, -0.77796288,  0.315862  ,  2.28607762],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.46305118, -0.75310701, -0.90742382,  0.61474453],
       [ 2.1697109 ,  0.70864324,  0.44073562,  0.48966493],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [-1.63379904, -0.75766892, -0.59356889,  0.45998309],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])